### ISSUE TITLE
std::cbegin() and std::cend() would require a compiler flag bump for gcc

### ISSUE THREAD

**Issue by carmichaelong** [tgeijten/flut#13]
`std::cbegin()` and `std::cend()` are supported starting with C++14, which would require a compiler flag bump on GCC 4.9.1 😞. Right now, the const methods are not needed (commenting these 3 out of [container_tools.hpp](https://github.com/tgeijten/flut/blob/master/flut/container_tools.hpp) will allow the code to compile. @tgeijten I'm unsure if it's worth it to do some weird workaround or not.

As a side note, [cma_optimizer.cpp](https://github.com/tgeijten/flut/blob/master/flut/optimizer/cma_optimizer.cpp) is missing a `#include <cstring>` for `strcmp`, `strncmp`, and `strcpy`.

**Comment by tgeijten** [comment]
Thanks,I'll add the #includes. About c++14, do you have a problem with this? Otherwise I would just change the compiler flag (it's 2017 😉).

**Comment by chrisdembia** [comment]
We would need to be able to compile OpenSim with c++14 with clang/gcc. We don't currently have a plan on supporting c++14 in the upcoming OpenSim 4.0 release, but hopefully we would support it soon after. As for OpenSim 3.3, I'm not sure we plan on supporting c++14.

**Comment by chrisdembia** [comment]
Then again, c++14 probably doesn't have many backwards incompatibilities that we would have to deal with. Just a matter of allowing the right flag to be specified with CMake.

**Comment by carmichaelong** [comment]
We should be able to look into the flag for OpenSim 3.3. I remember at one point I tried to compile Simbody 3.5.3 with C++14 (using a later version of GCC) and the tests were failing, but to be fair, I didn't try too hard to make it work... That being said, Chris is probably right that it shouldn't be too bad to get working so should be fine to keep some C++14 stuff in.

**Comment by tgeijten** [comment]
I compiled Simbody 3.5.3 and OpenSim 3.3 with Visual Studio 2015 (x64), both without problems. VS 2015 supports C++14 (albeit partly) by default. Can you try to bump to C++14 and see what happens?

C++14 should be backwards compatible, as long as you don’t declare anything in the std namespace, or have a conflicts through a “using namespace std” statement.

Thomas

**Comment by chrisdembia** [comment]
@tgeijten do you plan to package OpenSim 3.3 with SCONE? That might be a good idea, since I'm not sure we should rely on a future OpenSim 3.3 C++14 (VS2015) binary release.

**Comment by tgeijten** [comment]
Are you talking about packaging the OpenSim API or the full application with GUI?

On 14 Feb 2017, at 16:47, Christopher Dembia <notifications@github.com<mailto:notifications@github.com>> wrote:


@tgeijten<https://github.com/tgeijten> do you plan to package OpenSim 3.3 with SCONE? That might be a good idea, since I'm not sure we should rely on a future OpenSim 3.3 C++14 (VS2015) binary release.

**Comment by chrisdembia** [comment]
Ah good point. I mean just the API, using the 3.3 source release (which only contains the API).

**Comment by carmichaelong** [comment]
Had some trouble at first with cmake detecting the wrong GCC to use, but after fixing that looks like we should be fine with C++14 with Simbody 3.5.3 and OpenSim 3.3.

**Comment by tgeijten** [comment]
Great! So we can use C++14 now?

**Comment by tgeijten** [comment]
Sure, Chris, I can include the OpenSim API in SCONE. In fact, it’s probably for the best since I’m using an unreleased branch, which fixes a bug in the 3.3 release that is relevant for predictive simulations.

On an unrelated note: I’m currently working on moving away from Shark and use the C-CMAES library for optimization in SCONE. So far, it has been quite a hassle (C-CMAES isn’t exactly well-designed code), but I’m sure it will work out. After that, we should be able to use Apache after all (except for the GUI, which still uses Qt).

Thomas

**Comment by carmichaelong** [comment]
Yes, feel free to use C++14. I'll make a PR soon to bump the compiler version requirements for GCC. I just wanted to keep this open while you guys were discussing other things about packaging. I'll close this issue now and if we need, we can make a new issue about packaging in the SCONE repository.

**Comment by chrisdembia** [comment]
> On an unrelated note: I’m currently working on moving away from Shark and use the C-CMAES library for optimization in SCONE. So far, it has been quite a hassle (C-CMAES isn’t exactly well-designed code), but I’m sure it will work out. After that, we should be able to use Apache after all (except for the GUI, which still uses Qt).

Woohoo! That's excellent. I hope it will improve the impact of SCONE.  

Consider looking at Simbody's CMAES. The interface for C-CMAES is not great, but you can see how I dealt with it over in Simbody.

**Comment by tgeijten** [comment]
Hi Chris,

Just checked out your CMAES code in Simbody, looks nice how you added a wrapper without having to change the original C-CMAES code! I had been trying to do something similar, but in the end I could not find a way to stop C-CMAES from outputting unwanted files without having to change the code… So I ended up cherry-picking and refactoring the C-CMAES library and added a clean C++ wrapper (it’s in the flut library). This is obviously not the best way to stay compatible, but since C-CMAES hasn’t been updated for a long time I hope that’s ok.

I did also included the boundary transformation which was also in C-CMAES, which is a better way to deal with parameter boundaries than simply resampling or clamping.

I think for the apache license, it is required to document the changes I made to the C-CMAES code, I still need to do that.

Thomas

**Comment by chrisdembia** [comment]
> I could not find a way to stop C-CMAES from outputting unwanted files without having to change the code… 

Ah yes...that was something I wish I able to address.

> I did also included the boundary transformation which was also in C-CMAES, which is a better way to deal with parameter boundaries than simply resampling or clamping.

Thank you for explaining this...I wasn't sure what the boundary transformation was for. Resampling definitely doesn't seem like the right way to do this...
